func check(_ condition: Bool, _ name: String) { precondition(condition, name); print("PASS: " + name) }
check(SpeechTextReconciler.removingOverlap("project today and tomorrow", after: "We discuss the project today") == "and tomorrow", "rotation overlap")
check(SpeechTextReconciler.removingOverlap("New topic now", after: "We discuss the project today") == "New topic now", "new words preserved")
check(SpeechTextReconciler.removingOverlap("Hello, WORLD! next", after: "hello world") == "next", "punctuation overlap")
check(SpeechTextReconciler.remainder("We meet today. Next item", committed: "We meet today") == "Next item", "sentence boundary")
check(SpeechTextReconciler.remainder("Actually we should meet today before lunch Next item", committed: "We should meet today before lunch") == "Next item", "revision before boundary")
check(SpeechTextReconciler.remainder("Hello", committed: "Hello there everyone") == "", "short partial does not reset")
check(SpeechTextReconciler.remainder("A new unrelated utterance", committed: "Last sentence done") == nil, "fresh utterance detected")
check(SpeechTextReconciler.keepLongerPartial("We need all these words", incoming: "We need", final: false) == "We need all these words", "short partial retained")
check(SpeechTextReconciler.keepLongerPartial("We need more work", incoming: "We need less work", final: false) == "We need less work", "correction allowed")

check(SpeechTextReconciler.keepLongerPartial("Ragnar true story is almost a mystery", incoming: "Ragnar true story is almost a", final: true) == "Ragnar true story is almost a mystery", "short final retains received words")
check(SpeechTextReconciler.removingOverlap("very important", after: "This is very") == "very important", "one-word repetition preserved")
check(CaptionSegmenter.chunks("We meet today. Next we review the plan.").count == 2, "complete sentences separated")
check(CaptionSegmenter.chunks("The rate is 3.14 percent today.").count == 1, "decimal remains in sentence")
let longText = Array(repeating: "word", count: 90).joined(separator: " ")
let chunks = CaptionSegmenter.chunks(longText)
check(chunks.count >= 4 && chunks.allSatisfy { SpeechTextReconciler.words($0).count <= 28 }, "unpunctuated speech bounded")
check(chunks.joined(separator: " ") == longText, "no words lost by splitting")
check(CaptionSegmenter.chunks(String(repeating: "中", count: 400)).allSatisfy { $0.count <= 160 }, "CJK length bounded")
check(SpeechTextReconciler.remainder("今天学习。明天练习", committed: "今天学习。") == "明天练习", "CJK committed boundary")
check(CaptionSegmenter.chunks("Dr. Smith will join us today.").count == 1, "abbreviated title stays with sentence")
let chineseText = String(repeating: "中文", count: 200)
check(CaptionSegmenter.chunks(chineseText).joined() == chineseText, "CJK characters preserved")
check(CaptionSegmenter.chunks("First sentence. Second sentence. Still speaking").last == "Still speaking", "unfinished tail retained")
